### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by demanuel** [demanuel/NewsUP#15]
Improve performance of newsup.

**Comment by demanuel** [comment]
The yenc encoding process is now in C.

**Comment by shillshocked** [comment]
Latest version give me this:

"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.
"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.
"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.
"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.
"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.
\C is deprecated in regex; marked by <-- HERE in m/(\C <-- HERE )/ at /usr/share/perl5/site_perl/URI/Escape.pm line 205.

no element found at line 2, column 0, byte 71 at /usr/lib/perl5/vendor_perl/XML/Parser.pm line 187.
 at /usr/bin/vendor_perl/xml_grep line 138.
 at /usr/bin/vendor_perl/xml_grep line 138.

**Comment by shillshocked** [comment]
Or when just trying one file:

"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.

**Comment by demanuel** [comment]
Please try it now 


     On Monday, September 7, 2015 11:24 PM, shillshocked <notifications@github.com> wrote:
   

 Or when just trying one file:"my" variable $subject masks earlier declaration in same scope at /home/phoenix/bin/NewsUP-master/newsup.pl line 481.
Global symbol "$uploadSize" requires explicit package name (did you forget to declare "my $uploadSize"?) at /home/phoenix/bin/NewsUP-master/newsup.pl line 259.
Execution of /home/phoenix/bin/NewsUP-master/newsup.pl aborted due to compilation errors.—

**Comment by demanuel** [comment]
Put the CRC32 calculation inside the yenc encoding, to improve the speed.
