### ISSUE TITLE
[metadata] mandatory in config file, -metadata provided in input parameter is not working, generated .nzb file contains segments with 0 bytes

### ISSUE THREAD

**Issue by kouze** [demanuel/NewsUP#27]
Hi again,

[metadata] section is mandatory in the config file. This is due to:
```%metadata = %{$config->{metadata}};```
which is not checking if $config->{metadata} is defined, as you have done with the other fields.

In addition, due to this line, I guess %metadata is reset to "whatever you've put in the config file", blank included, and then what you've provided as input parameter is lost.

Third light issue is that the .nzb contains segment with 0 bytes. I have generated rar file which size is a multiple of the segment size. Here 52224000 bytes, which should generate 68 segments with each 768000 bytes (the size of my segment size !).
Unfortunately, the last segment (the 68th) in the .nzb for all these files has a size of "0". I guess it should be 768000, right?
Well the .nzb is still working with nzbget, it is not throwing any issue, but I'm still thinking it's not correct.
If you look at the size of the .sfv file, the file has a size of 1441 bytes, and the segment has a size of 1441 bytes as well, so there is a match.

Find the generated file here: https://mega.nz/#!PplUBaKK!orp8lXggzIe3EhOMezlukQniJJCHyEj1AnR7IzgOZVQ

**Comment by demanuel** [comment]
Excelent analysis.

The metadata passed on the command line was being overwritten (without any checking) by the one in the config file.

It's now fixed.

Regarding the size 0, that was something that i never thought about it, since it's a special case. 

To avoid storing info which 99.999% are redundant, i don't store the segment size. And initially all the segments in the NZB were having as size the value of $NNTP_MAX_UPLOAD_SIZE.

So on the first version:
```
$bytes =  $NNTP_MAX_UPLOAD_SIZE
```
Most of the clients ignore the size, because they get it from the post itself (the yenc specification requires the size in the headers) and not from the NZB itself. However some not very well known clients get the size from the nzb, and i started getting complains because the size didn't match. But it was only for the last segment, because all the uploads are done with $NNT_MAX_UPLOAD_SIZE, except if the data available is less than that, which is only on the last segment that happens. So on the second version of the size:

```
$bytes =  $segment-> {fileSize} % $NNTP_MAX_UPLOAD_SIZE if($segment->{segmentNumber} == $segment->{totalSegments});
```

But your case is a special case (what are the odds of the filesize be a multiple of NNTP_MAX_UPLOAD_SIZE ? :-) ).
So i just changed it to:
```
    $bytes =  $segment-> {fileSize} % $NNTP_MAX_UPLOAD_SIZE if($segment->{segmentNumber} == $segment->{totalSegments});
    $bytes = $NNTP_MAX_UPLOAD_SIZE if $bytes == 0;
```

Please check the latest version.

**Comment by kouze** [comment]
Hi demanuel,

your fix looks good to me :)

Thanks again !

**Comment by demanuel** [comment]
cool! :+1:
