### ISSUE TITLE
What order are the files uploaded?

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#29]
With the new code, is it alphabetical, semi-alphabetical depending on error conditions, or by date of the file?

**Comment by demanuel** [comment]
The upload is **started** by the order you specify with the -f.

I'm saying started, because even if a file isn't finished and there's connection available then the next file is started. This way it's impossible to say if the files will be uploaded in order, but i can only that they will start in order.

Example:
2 connections, 3 files (one with 3 segments (file a), 2 with one segment (file b and c)).

* If you do -f A -f B -f C, what will probably happen is that

Segment 1 of A is uploaded
Segment 2 of A is uploaded
Segment 3 of A is being uploaded
Segment 1 of B is being uploaded
Segment 1 of C is on wait

There's a race between file A and file B to finish. I don't know which one will be uploaded first.

* If you do -f B -f A -f C, what will probably happen is that

Segment 1 of B is uploaded
Segment 1 of A is uploaded
Segment 2 of A is uploaded
Segment 3 of A is being uploaded
Segment 1 of C is being uploaded

There's a race between file A and file C to finish. I don't know which one will be uploaded first.



And so on...
