### ISSUE TITLE
Astraweb 502 error

### ISSUE THREAD

**Issue by BytesBacon** [demanuel/NewsUP#37]
This seems limited to Astraweb only, from all the providers I've tested. (But it could be more, as it's very rare, just really annoying when it happens.)

`Error: 502 Your per-user connection limit reached`

The program hits this error and runs the die command to end. Which shouldn't be needed.

From Astraweb [site](http://helpdesk.astraweb.com/index.php?_m=troubleshooter&_a=steps&troubleshootercatid=3&parentid=0):

> This means that you are connecting to our server too many times. You might have set your connection limit on your newsreader too high.
>
> Newsreaders use connections to download headers as well, so if you set your connections to the maximum limit, you will find that you get these errors.
> 
> Please ensure that you do not set your connections to the maximum limit. 6-8 connections is usually enough.
> 
> Also, please note that your connection limit is spread across all servers types (SSL, normal, EU and US).

I'm not sure if the call is coming from the _read_from_socket or _authenticate function when the error hits (or I'd try and come up with a fix myself), but I believe adding another if statement with regex looking for 502 and if provider Astraweb (not sure if other providers have this same issue, as I haven't seen yet) make sure the socket connects are dropped or add a sleep for X secs (as personal I think Astraweb servers are hanging the connection when it's closed).

Sabnzbd had an issue like this, [commit](https://github.com/sabnzbd/sabnzbd/commit/6296fc1762386a5b6fbde7e664f3f1593916b445)

Depending on the status code replied from the server, it'll limit the connections by X and after Y delay increase the connections back to the config for that server. I'm thinking something like this would fix the error 502 issue.

Thanks

**Comment by demanuel** [comment]
If you're getting the error "502 Your per-user connection limit reached", why don't you decrease the connection number? You're trying to use too many connections...

Some providers take some time (a couple of minutes, nothing much) to update the connection counters.

Btw, that message is when authenticating. That's why the program exits. Otherwise i always try to recover.

**Comment by BytesBacon** [comment]
This was with 40 out of 50 connections, the upload finished and the delay started in the function _start_header_check, after the delay that's when the 502 message hit.

If it was at the start of uploading or was over the amount of connections I would understand, but this is after uploading. And b/c the program hits this while checking if all the segments are uploaded, it never finishes to make the NZB file. The program dies, the nzb doesn't get made b/c the function _create_nzb is called after the _start_header_check runs and that's when I'm seeing the 502 on Astraweb.

**Comment by demanuel** [comment]
When an upload finishes it will close all the connections. 
To perform the header checking it will create new connections. After the header check finishes the connections are closed. 

So with header check you have at least 2 places where new connections are created.
It's supposed to die when establishing the connections, in order to force the user to put a correct number. And as i told previously some servers take a little more time to update the connection counters.

At this moment, you have a workaround for issue you're seing in the headercheck:
1- Change the configurations to use a different server for headerchecking, where you aren't logged in so you can't suffer that problem.
2- increase the header check sleep to give time to the server to update the logins properly.


Anyway, i'm going to change the code for when the connections are being established on the headercheck if they fail with that message, to not die.

**Comment by demanuel** [comment]
Please check the latest commit.

**Comment by BytesBacon** [comment]
Working with the new committed version, however tho there is a new issue, that looks like it was from commit before, [9f0b1da0865a6fd599176be130da61cf6ce2182f](https://github.com/demanuel/NewsUP/commit/9f0b1da0865a6fd599176be130da61cf6ce2182f)

The program no longer listens to the config first, but to the default settings in the code.

```
#Default Header check values
my $headerCheck = 0;
my $headerCheckRetries = 3; #Number of retries to be done in case the user decides to go for a headerCheck
my $headerCheckSleep = 20;
```

Then later down in the code, this runs

```
if (!defined $headerCheckSleep) {
    if (exists $config->{headerCheck}{sleep}){
        $headerCheckSleep = $config->{headerCheck}{sleep};
    }else {
         $headerCheckSleep=20;
    }
}
```

B/c $headerCheckSleep was already defined, this code above gets skipped and the config options are never used. The Sleep stays at the 20 and not the 120 that I have set for Astraweb (as it needs a longer delay).

For the moment, as I'm testing the main changes, I've just updated the values in the code. But for everyone else, this means the 'headerCheck' values in the config will not be used right.

**Comment by demanuel** [comment]
Let's check the code...

It starts with this:

```
#Default Header check values
my $headerCheck = 0;
my $headerCheckRetries = 3; #Number of retries to be done in case the user decides to go for a headerCheck
my $headerCheckSleep = 20;
```

This is the default values when you use the command line. If you notice a bit further down in the code you'll see:

```
  if(!$headerCheck){
    undef $headerCheckRetries;
    undef $headerCheckSleep;
    undef $headerCheckConnections;
    undef $headerCheckServer;
    undef $headerCheckPort;
    undef $headerCheckUserName;
    undef $headerCheckPassword;
  }
```

So it's undef'ing the values if the headercheck isn't being set on the command line.Then after this, it will check if the configuration file exists and it will load the values for the headercheck:

```
    if (!defined $headerCheck) {
      $headerCheck = $config->{headerCheck}{enabled} if exists $config->{headerCheck}{enabled};
    }
```
and this condition is wrong! because now the headercheck is defined by default. 

It should be only 

`$headerCheck = $config->{headerCheck}{enabled} if exists $config->{headerCheck}{enabled};`



Please check the latest commit.

**Comment by BytesBacon** [comment]
That fixed the config issues I was having now.

But I'm now seeing a issue with this block of code.

```
      for my $socket (@$readers){
        my $output = _read_from_socket($socket);
        $missingReads--;
        print int((++$countProgress / $totalMissingSegments)*100),"%\r";
        if ($output =~ /^223 \d <(.+)>/) {
          delete $candidates{$1};
        }elsif ($output =~ /^400 /) {
          shutdown ($socket, 2);
          undef $socket;
          my $conList = _get_connections(1, $headerCheckServer, $headerCheckPort, $headerCheckUsername, $headerCheckPassword);
        }
      }
```

On Astraweb and Blocknews (and maybe others, haven't tested yet) for some reason this is hanging at 99%, all of the 99% reports as 223 (as I added some debugging msg to know what's going on). But after 99% it just hangs doesn't continue in the loop and I'm not sure why. However tho, the CPU hits 100% (on one thread) for the script when looking at htop.

Example reply from Blocknews: 
223 0 <348857382901828462.N327FDJDF3@EFH0751UTL.newsup>

Example reply from Astraweb:
223 0 <432767382916736494.C7328DFSFE@EFH1PRYCTY.newsup> status

Which that code looks to be changed in commit 9f0b1da0865a6fd599176be130da61cf6ce2182f

Thanks for looking into the issue.

**Comment by demanuel** [comment]
The only thing that i found was the connection that is getting shutdown (in case of a missing segment is found) wasn't being removed from the select.

All the tests were normal, as they did before. I'm not seeing anything else. Please report if the issue persists.

**Comment by BytesBacon** [comment]
That's working now, was odd how it was just hanging.

Started to run a few more test, and on Astraweb hit this one.

```
Warping up header check engines with 40 connections!
Can't call method "connected" on unblessed reference at /usr/bin/newsup line 785.
```

https://github.com/demanuel/NewsUP/blob/master/newsup.pl#L785

`return "400 Socket closed\r\n" if (! $socket->connected);`

Most likely just something buggy with Astraweb. I'll run some more test with other providers and see, but that error has happened twice in a row with Astraweb.

**Comment by demanuel** [comment]
It looks like the number of connections that i'm returning isn't correct. It looks like the number of connections is short by one.

Please check the latest commit.

**Comment by BytesBacon** [comment]
Still happening on Astraweb.

It seems to be with the changes made in _start_header_check that have the CPU spike when I put perl in debugger mode and go though it. ([Older version](https://github.com/demanuel/NewsUP/blob/303a209ab185de5ea8b6a733df827a7f6c4f1cee/newsup.pl#L445) still works, but has other issues as you know.)

Seems to be, https://github.com/demanuel/NewsUP/blob/master/newsup.pl#L498 call 

That's when the percentage locks up, the CPU usage goes 100% for the thread and only seems to be Astraweb.

With Cheapnews, it uploads fine but when in the function _start_header_check loops around this https://github.com/demanuel/NewsUP/blob/master/newsup.pl#L793

So I'm not sure if it's all related L498 and L798.

Interested in using an Astraweb account for testing?

Tested so far Astraweb, Blocknews, Cheapnews, Usenet-news and XSnews. Got to get more accounts for more testing.

**Comment by demanuel** [comment]
If you have some temporary test accounts on those two problematics servers can you please send me an email with the info?

> That's when the percentage locks up, the CPU usage goes 100% for the thread and only seems to be Astraweb.

This is a symptom that it's in an infinite loop. Which is odd, since everytime it reads something it decreases the counter... Maybe all the connections are dead, and we still have segments to read?

> With Cheapnews, it uploads fine but when in the function _start_header_check loops around this https://github.com/demanuel/NewsUP/blob/master/newsup.pl#L793

This makes no sense. The reading function is the same everywhere.... If there was a problem, it should complain on the first read.

If you have some test account that you could borrow me for 1 week, it would be great.

Regards,
David

**Comment by demanuel** [comment]
Are these issues fixed? Can i close it?

**Comment by demanuel** [comment]
I'm closing this. Feel free to re-open it.
