### ISSUE TITLE
Option to use Message-IDs provided by usenet server

### ISSUE THREAD

**Issue by L2501** [demanuel/NewsUP#38]
using local ids leaks information
xsnews doesnt send you the Message-ID so generating nzb will be impossible on there, other servers send you the id following post command

**Comment by demanuel** [comment]
> using local ids leaks information

This is new to me. Can you explain this more?

The IDs are generated in this function: 
https://github.com/demanuel/NewsUP/blob/master/newsup.pl#L897

The only thing that it is used to generate it is the current timestamp in microseconds, so no other info can be leaked.

> xsnews doesnt send you the Message-ID so generating nzb will be impossible on there, other servers send you the id following post command

Exactly. This is a can of worms that i don't want to open, since i would have to change the algorithm in order to deal with such exceptions, for no obvious gain.

**Comment by demanuel** [comment]
I'm closing this as the request

> Can you explain this more?

was not fullfilled. Since there are no new info doesn't make sense to have this open.
Please re-open it if requried.

**Comment by demanuel** [comment]
I implemented this.

Now it uses the ID provided by the newsgroup. I'm not generating the IDs anymore.
Please check the latest commit.
