### ISSUE TITLE
Sequential File Uploading

### ISSUE THREAD

**Issue by shillshocked** [demanuel/NewsUP#7]
Good for those who need it. When you're posting a batch of stuff, it's useful to keep organized so you know it's all posted, as well as for the user who downloads it to ensure they got the whole batch.

**Comment by demanuel** [comment]
To be implemented in the future

**Comment by shillshocked** [comment]
The script is great, but is there any way to get the segments in the nzb to be in order?

**Comment by demanuel** [comment]
I just updated the newsup to create a nzb with the segments in order. This way the script should work fine. Can you please test it?

**Comment by shillshocked** [comment]
The nzb is still unsorted.

**Comment by demanuel** [comment]
Shoot... You are right. The segments are only being in correct order if you have only one connection.

Anyway now it's fixed!

**Comment by demanuel** [comment]
@shillshocked i've been thinking in this and i can't guarantee this.
Imagine that we have 3 files, and 50 connections.
And each of the file is split in 20 parts. So we have 60 parts and 50 connections.

In order to be the fastest possible, i want to start the upload as soon as possible.
so I start 20 uploads of file 1, 20 uploads of file 2 and 10 uploads of file 3.

So it's impossible to me to know the final order of the files to be uploaded...

**Comment by shillshocked** [comment]
Why don't you just split each uploaded file into x connections of the server, ie. 50?

**Comment by demanuel** [comment]
There's a problem with that. It would make the upload size very big or very small ( issue #4 ).

**Comment by shillshocked** [comment]
I've never had that issue using Jbinup or gopoststuff.

**Comment by demanuel** [comment]
Thats because they wait for a file to be completely uploaded before starting other file. So the upload size doesn't matter, but then like i said previously i want to start (and consequently,finishing) the uploads as soon as possible.

**Comment by demanuel** [comment]
There's no progress with this issue.
I'm going to leave it open, but locked, so it doesn't disappear.

**Comment by demanuel** [comment]
This will not be implemented. I'm closing.
